import { PrismaClient } from '@prisma/client';
import { generateSetSlug, generateCardSlug } from '../../lib/slugGenerator';

const prisma = new PrismaClient();

type C = [string, string, string, number | null];
const calcRarity = (pr: number | null) => !pr ? null : pr === 1 ? 'one_of_one' : pr <= 10 ? 'ultra_rare' : pr <= 50 ? 'super_rare' : pr <= 199 ? 'rare' : 'base';
const fmtNum = (pr: number | null) => !pr ? null : pr === 1 ? '1 of 1' : `/${pr}`;
interface S { n: string; c: C[]; p?: boolean; b?: string; m?: boolean }

const sets: S[] = [
  // Hall Dominator Signatures + parallels (30 cards each = 90 total)
  { n: 'Hall Dominator Signatures', c: [
    ['1','Dan Issel','Denver Nuggets',49],['2','Artis Gilmore','San Antonio Spurs',49],['3','Adrian Dantley','Detroit Pistons',49],['4','Tom Heinsohn','Boston Celtics',49],['5','Elvin Hayes','Baltimore Bullets',49],['6','Jamaal Wilkes','Los Angeles Lakers',49],['7','Tom "Satch" Sanders','Boston Celtics',49],['8','David Robinson','San Antonio Spurs',49],['9','Rick Barry','Golden State Warriors',49],['10','Bob Lanier','Detroit Pistons',25],['11','Dennis Rodman','Chicago Bulls',49],['12','David Thompson','Denver Nuggets',49],['13','John Stockton','Utah Jazz',49],['14','Alex English','Denver Nuggets',25],['15','Bernard King','New York Knicks',25],['16','Oscar Robertson','Milwaukee Bucks',49],['17','Hakeem Olajuwon','Houston Rockets',25],['18','Kevin McHale','Boston Celtics',25],['19','Earl Lloyd','Detroit Pistons',25],['20','Calvin Murphy','Houston Rockets',25],['21','Nate Thurmond','Golden State Warriors',25],['22','Cliff Hagan','St. Louis Hawks',25],['23','Robert Parish','Boston Celtics',25],['24','Wes Unseld','Washington Bullets',25],['25','Earl Monroe','New York Knicks',25],['26','Gary Payton','Seattle Supersonics',25],['27','Gail Goodrich','Phoenix Suns',25],['28','Willis Reed','New York Knicks',25],['29','Arvydas Sabonis','Portland Trail Blazers',25],['30','Dominique Wilkins','Atlanta Hawks',25]
  ] },
  { n: 'Hall Dominator Signatures Black', p: true, b: 'Hall Dominator Signatures', c: [
    ['1','Dan Issel','Denver Nuggets',1],['2','Artis Gilmore','San Antonio Spurs',1],['3','Adrian Dantley','Detroit Pistons',1],['4','Tom Heinsohn','Boston Celtics',1],['5','Elvin Hayes','Baltimore Bullets',1],['6','Jamaal Wilkes','Los Angeles Lakers',1],['7','Tom "Satch" Sanders','Boston Celtics',1],['8','David Robinson','San Antonio Spurs',1],['9','Rick Barry','Golden State Warriors',1],['10','Bob Lanier','Detroit Pistons',1],['11','Dennis Rodman','Chicago Bulls',1],['12','David Thompson','Denver Nuggets',1],['13','John Stockton','Utah Jazz',1],['14','Alex English','Denver Nuggets',1],['15','Bernard King','New York Knicks',1],['16','Oscar Robertson','Milwaukee Bucks',1],['17','Hakeem Olajuwon','Houston Rockets',1],['18','Kevin McHale','Boston Celtics',1],['19','Earl Lloyd','Detroit Pistons',1],['20','Calvin Murphy','Houston Rockets',1],['21','Nate Thurmond','Golden State Warriors',1],['22','Cliff Hagan','St. Louis Hawks',1],['23','Robert Parish','Boston Celtics',1],['24','Wes Unseld','Washington Bullets',1],['25','Earl Monroe','New York Knicks',1],['26','Gary Payton','Seattle Supersonics',1],['27','Gail Goodrich','Phoenix Suns',1],['28','Willis Reed','New York Knicks',1],['29','Arvydas Sabonis','Portland Trail Blazers',1],['30','Dominique Wilkins','Atlanta Hawks',1]
  ] },
  { n: 'Hall Dominator Signatures Gold', p: true, b: 'Hall Dominator Signatures', c: [
    ['1','Dan Issel','Denver Nuggets',10],['2','Artis Gilmore','San Antonio Spurs',10],['3','Adrian Dantley','Detroit Pistons',10],['4','Tom Heinsohn','Boston Celtics',10],['5','Elvin Hayes','Baltimore Bullets',10],['6','Jamaal Wilkes','Los Angeles Lakers',10],['7','Tom "Satch" Sanders','Boston Celtics',10],['8','David Robinson','San Antonio Spurs',10],['9','Rick Barry','Golden State Warriors',10],['10','Bob Lanier','Detroit Pistons',10],['11','Dennis Rodman','Chicago Bulls',10],['12','David Thompson','Denver Nuggets',10],['13','John Stockton','Utah Jazz',10],['14','Alex English','Denver Nuggets',10],['15','Bernard King','New York Knicks',10],['16','Oscar Robertson','Milwaukee Bucks',10],['17','Hakeem Olajuwon','Houston Rockets',10],['18','Kevin McHale','Boston Celtics',10],['19','Earl Lloyd','Detroit Pistons',10],['20','Calvin Murphy','Houston Rockets',10],['21','Nate Thurmond','Golden State Warriors',10],['22','Cliff Hagan','St. Louis Hawks',10],['23','Robert Parish','Boston Celtics',10],['24','Wes Unseld','Washington Bullets',10],['25','Earl Monroe','New York Knicks',10],['26','Gary Payton','Seattle Supersonics',10],['27','Gail Goodrich','Phoenix Suns',10],['28','Willis Reed','New York Knicks',10],['29','Arvydas Sabonis','Portland Trail Blazers',10],['30','Dominique Wilkins','Atlanta Hawks',10]
  ] },
  // Next Day Signatures (39 cards, unnumbered)
  { n: 'Next Day Signatures', c: [
    ['1','Brandon Ingram','Los Angeles Lakers',null],['2','Jaylen Brown','Boston Celtics',null],['3','Dragan Bender','Phoenix Suns',null],['4','Kris Dunn','Minnesota Timberwolves',null],['5','Buddy Hield','New Orleans Pelicans',null],['6','Jamal Murray','Denver Nuggets',null],['7','Marquese Chriss','Phoenix Suns',null],['8','Jakob Poeltl','Toronto Raptors',null],['9','Thon Maker','Milwaukee Bucks',null],['10','Taurean Prince','Atlanta Hawks',null],['11','Georgios Papagiannis','Sacramento Kings',null],['12','Denzel Valentine','Chicago Bulls',null],['13','Juan Hernangomez','Denver Nuggets',null],['14','Wade Baldwin IV','Memphis Grizzlies',null],['15','Henry Ellenson','Detroit Pistons',null],['16','Caris LeVert','Brooklyn Nets',null],['17','DeAndre\' Bembry','Atlanta Hawks',null],['18','Malachi Richardson','Sacramento Kings',null],['19','Timothe Luwawu-Cabarrot','Philadelphia 76ers',null],['20','Brice Johnson','Los Angeles Clippers',null],['21','Pascal Siakam','Toronto Raptors',null],['22','Skal Labissiere','Sacramento Kings',null],['23','Dejounte Murray','San Antonio Spurs',null],['24','Damian Jones','Golden State Warriors',null],['25','Deyonta Davis','Memphis Grizzlies',null],['26','Cheick Diallo','New Orleans Pelicans',null],['27','Tyler Ulis','Phoenix Suns',null],['28','Patrick McCaw','Golden State Warriors',null],['29','Malcolm Brogdon','Milwaukee Bucks',null],['30','Isaiah Whitehead','Brooklyn Nets',null],['31','Demetrius Jackson','Boston Celtics',null],['32','Kay Felder','Cleveland Cavaliers',null],['33','Gary Payton II','Houston Rockets',null],['34','Diamond Stone','Los Angeles Clippers',null],['35','Ivica Zubac','Los Angeles Lakers',null],['36','Chinanu Onuaku','Houston Rockets',null],['37','Stephen Zimmerman','Orlando Magic',null],['38','A.J. Hammons','Dallas Mavericks',null],['39','Malik Beasley','Denver Nuggets',null]
  ] },
  // Rookie Dominator Signatures + parallels (30 cards each = 90 total)
  { n: 'Rookie Dominator Signatures', c: [
    ['1','Stephen Zimmerman','Orlando Magic',50],['2','Marquese Chriss','Phoenix Suns',65],['3','Buddy Hield','New Orleans Pelicans',65],['4','Henry Ellenson','Detroit Pistons',65],['5','Georges Niang','Indiana Pacers',65],['6','Demetrius Jackson','Boston Celtics',65],['7','Isaiah Whitehead','Brooklyn Nets',50],['8','Thon Maker','Milwaukee Bucks',65],['9','Domantas Sabonis','Oklahoma City Thunder',65],['10','Dragan Bender','Phoenix Suns',65],['11','Timothe Luwawu-Cabarrot','Philadelphia 76ers',65],['12','Ivica Zubac','Los Angeles Lakers',65],['13','Damian Jones','Golden State Warriors',65],['14','Tyler Ulis','Phoenix Suns',65],['15','Kris Dunn','Minnesota Timberwolves',50],['16','Deyonta Davis','Memphis Grizzlies',65],['17','Brandon Ingram','Los Angeles Lakers',50],['18','Jamal Murray','Denver Nuggets',65],['19','Denzel Valentine','Chicago Bulls',65],['20','Jakob Poeltl','Toronto Raptors',65],['21','Skal Labissiere','Sacramento Kings',50],['22','Caris LeVert','Brooklyn Nets',65],['23','Diamond Stone','Los Angeles Clippers',65],['24','Chinanu Onuaku','Houston Rockets',65],['25','Brice Johnson','Los Angeles Clippers',65],['26','Malik Beasley','Denver Nuggets',65],['27','Wade Baldwin IV','Memphis Grizzlies',65],['28','Daniel Hamilton','Oklahoma City Thunder',60],['29','Kay Felder','Cleveland Cavaliers',65],['30','Michael Gbinije','Detroit Pistons',50]
  ] },
  { n: 'Rookie Dominator Signatures Black', p: true, b: 'Rookie Dominator Signatures', c: [
    ['1','Stephen Zimmerman','Orlando Magic',1],['2','Marquese Chriss','Phoenix Suns',1],['3','Buddy Hield','New Orleans Pelicans',1],['4','Henry Ellenson','Detroit Pistons',1],['5','Georges Niang','Indiana Pacers',1],['6','Demetrius Jackson','Boston Celtics',1],['7','Isaiah Whitehead','Brooklyn Nets',1],['8','Thon Maker','Milwaukee Bucks',1],['9','Domantas Sabonis','Oklahoma City Thunder',1],['10','Dragan Bender','Phoenix Suns',1],['11','Timothe Luwawu-Cabarrot','Philadelphia 76ers',1],['12','Ivica Zubac','Los Angeles Lakers',1],['13','Damian Jones','Golden State Warriors',1],['14','Tyler Ulis','Phoenix Suns',1],['15','Kris Dunn','Minnesota Timberwolves',1],['16','Deyonta Davis','Memphis Grizzlies',1],['17','Brandon Ingram','Los Angeles Lakers',1],['18','Jamal Murray','Denver Nuggets',1],['19','Denzel Valentine','Chicago Bulls',1],['20','Jakob Poeltl','Toronto Raptors',1],['21','Skal Labissiere','Sacramento Kings',1],['22','Caris LeVert','Brooklyn Nets',1],['23','Diamond Stone','Los Angeles Clippers',1],['24','Chinanu Onuaku','Houston Rockets',1],['25','Brice Johnson','Los Angeles Clippers',1],['26','Malik Beasley','Denver Nuggets',1],['27','Wade Baldwin IV','Memphis Grizzlies',1],['28','Daniel Hamilton','Oklahoma City Thunder',1],['29','Kay Felder','Cleveland Cavaliers',1],['30','Michael Gbinije','Detroit Pistons',1]
  ] },
  { n: 'Rookie Dominator Signatures Gold', p: true, b: 'Rookie Dominator Signatures', c: [
    ['1','Stephen Zimmerman','Orlando Magic',10],['2','Marquese Chriss','Phoenix Suns',10],['3','Buddy Hield','New Orleans Pelicans',10],['4','Henry Ellenson','Detroit Pistons',10],['5','Georges Niang','Indiana Pacers',10],['6','Demetrius Jackson','Boston Celtics',10],['7','Isaiah Whitehead','Brooklyn Nets',10],['8','Thon Maker','Milwaukee Bucks',10],['9','Domantas Sabonis','Oklahoma City Thunder',10],['10','Dragan Bender','Phoenix Suns',10],['11','Timothe Luwawu-Cabarrot','Philadelphia 76ers',10],['12','Ivica Zubac','Los Angeles Lakers',10],['13','Damian Jones','Golden State Warriors',10],['14','Tyler Ulis','Phoenix Suns',10],['15','Kris Dunn','Minnesota Timberwolves',10],['16','Deyonta Davis','Memphis Grizzlies',10],['17','Brandon Ingram','Los Angeles Lakers',10],['18','Jamal Murray','Denver Nuggets',10],['19','Denzel Valentine','Chicago Bulls',10],['20','Jakob Poeltl','Toronto Raptors',10],['21','Skal Labissiere','Sacramento Kings',10],['22','Caris LeVert','Brooklyn Nets',10],['23','Diamond Stone','Los Angeles Clippers',10],['24','Chinanu Onuaku','Houston Rockets',10],['25','Brice Johnson','Los Angeles Clippers',10],['26','Malik Beasley','Denver Nuggets',10],['27','Wade Baldwin IV','Memphis Grizzlies',10],['28','Daniel Hamilton','Oklahoma City Thunder',10],['29','Kay Felder','Cleveland Cavaliers',10],['30','Michael Gbinije','Detroit Pistons',10]
  ] },
  // Rookie Materials Signatures + Prime (35 cards each = 70 total, AUTO+MEM)
  { n: 'Rookie Materials Signatures', m: true, c: [
    ['1','Brandon Ingram','Los Angeles Lakers',75],['2','Jaylen Brown','Boston Celtics',75],['3','Dragan Bender','Phoenix Suns',75],['4','Kris Dunn','Minnesota Timberwolves',75],['5','Buddy Hield','New Orleans Pelicans',75],['6','Jamal Murray','Denver Nuggets',75],['7','Marquese Chriss','Phoenix Suns',75],['8','Jakob Poeltl','Toronto Raptors',75],['9','Thon Maker','Milwaukee Bucks',75],['10','Taurean Prince','Atlanta Hawks',75],['11','Denzel Valentine','Chicago Bulls',75],['12','Wade Baldwin IV','Memphis Grizzlies',75],['13','Henry Ellenson','Detroit Pistons',75],['14','Malik Beasley','Denver Nuggets',75],['15','Caris LeVert','Brooklyn Nets',75],['16','DeAndre\' Bembry','Atlanta Hawks',75],['17','Malachi Richardson','Sacramento Kings',75],['18','Timothe Luwawu-Cabarrot','Philadelphia 76ers',75],['19','Brice Johnson','Los Angeles Clippers',75],['20','Pascal Siakam','Toronto Raptors',75],['21','Skal Labissiere','Sacramento Kings',75],['22','Dejounte Murray','San Antonio Spurs',75],['23','Damian Jones','Golden State Warriors',75],['24','Deyonta Davis','Memphis Grizzlies',75],['25','Ivica Zubac','Los Angeles Lakers',75],['26','Cheick Diallo','New Orleans Pelicans',75],['27','Tyler Ulis','Phoenix Suns',75],['28','Isaiah Whitehead','Brooklyn Nets',75],['29','Demetrius Jackson','Boston Celtics',75],['30','Kay Felder','Cleveland Cavaliers',75],['31','Gary Payton II','Houston Rockets',75],['32','Diamond Stone','Los Angeles Clippers',75],['33','Malcolm Brogdon','Milwaukee Bucks',75],['34','Chinanu Onuaku','Houston Rockets',75],['35','Patrick McCaw','Golden State Warriors',75]
  ] },
  { n: 'Rookie Materials Signatures Prime', p: true, b: 'Rookie Materials Signatures', m: true, c: [
    ['1','Brandon Ingram','Los Angeles Lakers',10],['2','Jaylen Brown','Boston Celtics',10],['3','Dragan Bender','Phoenix Suns',10],['4','Kris Dunn','Minnesota Timberwolves',10],['5','Buddy Hield','New Orleans Pelicans',10],['6','Jamal Murray','Denver Nuggets',10],['7','Marquese Chriss','Phoenix Suns',10],['8','Jakob Poeltl','Toronto Raptors',10],['9','Thon Maker','Milwaukee Bucks',10],['10','Taurean Prince','Atlanta Hawks',10],['11','Denzel Valentine','Chicago Bulls',10],['12','Wade Baldwin IV','Memphis Grizzlies',10],['13','Henry Ellenson','Detroit Pistons',10],['14','Malik Beasley','Denver Nuggets',10],['15','Caris LeVert','Brooklyn Nets',10],['16','DeAndre\' Bembry','Atlanta Hawks',10],['17','Malachi Richardson','Sacramento Kings',10],['18','Timothe Luwawu-Cabarrot','Philadelphia 76ers',10],['19','Brice Johnson','Los Angeles Clippers',10],['20','Pascal Siakam','Toronto Raptors',10],['21','Skal Labissiere','Sacramento Kings',10],['22','Dejounte Murray','San Antonio Spurs',10],['23','Damian Jones','Golden State Warriors',10],['24','Deyonta Davis','Memphis Grizzlies',10],['25','Ivica Zubac','Los Angeles Lakers',10],['26','Cheick Diallo','New Orleans Pelicans',10],['27','Tyler Ulis','Phoenix Suns',10],['28','Isaiah Whitehead','Brooklyn Nets',10],['29','Demetrius Jackson','Boston Celtics',10],['30','Kay Felder','Cleveland Cavaliers',10],['31','Gary Payton II','Houston Rockets',10],['32','Diamond Stone','Los Angeles Clippers',10],['33','Malcolm Brogdon','Milwaukee Bucks',10],['34','Chinanu Onuaku','Houston Rockets',10],['35','Patrick McCaw','Golden State Warriors',10]
  ] },
  // Signature Series + Gold (50 cards each = 100 total)
  { n: 'Signature Series', c: [
    ['1','Cody Zeller','Charlotte Hornets',null],['2','C.J. McCollum','Portland Trail Blazers',null],['3','Ian Clark','Golden State Warriors',null],['4','Dwight Powell','Dallas Mavericks',null],['5','Josh Huestis','Oklahoma City Thunder',null],['6','T.J. McConnell','Philadelphia 76ers',null],['7','James Ennis','Memphis Grizzlies',null],['8','Walter Tavares','Atlanta Hawks',null],['9','Alex Len','Phoenix Suns',null],['10','Allen Crabbe','Portland Trail Blazers',null],['11','Noah Vonleh','Portland Trail Blazers',null],['12','Aaron Harrison','Charlotte Hornets',null],['13','Kevon Looney','Golden State Warriors',null],['14','Tristan Thompson','Cleveland Cavaliers',null],['15','C.J. Miles','Indiana Pacers',null],['16','Dirk Nowitzki','Dallas Mavericks',null],['17','Kyle O\'Quinn','New York Knicks',null],['18','Jeff Withey','Utah Jazz',null],['19','Jonas Valanciunas','Toronto Raptors',null],['20','Rashad Vaughn','Milwaukee Bucks',null],['21','Seth Curry','Dallas Mavericks',null],['22','Deron Williams','Dallas Mavericks',null],['23','D\'Angelo Russell','Los Angeles Lakers',null],['24','Kelly Olynyk','Boston Celtics',null],['25','Michael Carter-Williams','Milwaukee Bucks',null],['26','Devin Harris','Dallas Mavericks',null],['27','Matthew Dellavedova','Milwaukee Bucks',null],['28','Montrezl Harrell','Houston Rockets',null],['29','Draymond Green','Golden State Warriors',null],['30','Langston Galloway','New Orleans Pelicans',null],['31','Glenn Robinson III','Indiana Pacers',null],['32','Robert Covington','Philadelphia 76ers',null],['33','Bobby Portis','Chicago Bulls',null],['34','Festus Ezeli','Portland Trail Blazers',null],['35','Jared Dudley','Phoenix Suns',null],['36','Justise Winslow','Miami Heat',null],['37','Shabazz Muhammad','Minnesota Timberwolves',null],['38','Jarell Martin','Memphis Grizzlies',null],['39','Terrence Jones','New Orleans Pelicans',null],['40','Timofey Mozgov','Los Angeles Lakers',null],['41','Al-Farouq Aminu','Portland Trail Blazers',null],['42','Khris Middleton','Milwaukee Bucks',null],['43','Tyus Jones','Minnesota Timberwolves',null],['44','Rodney Stuckey','Indiana Pacers',null],['45','Luc Mbah a Moute','Los Angeles Clippers',null],['46','Brandon Rush','Minnesota Timberwolves',null],['47','James Young','Boston Celtics',null],['48','Avery Bradley','Boston Celtics',null],['49','Kristaps Porzingis','New York Knicks',null],['50','Anthony Bennett','Brooklyn Nets',null]
  ] },
  { n: 'Signature Series Gold', p: true, b: 'Signature Series', c: [
    ['1','Cody Zeller','Charlotte Hornets',10],['2','C.J. McCollum','Portland Trail Blazers',10],['3','Ian Clark','Golden State Warriors',10],['4','Dwight Powell','Dallas Mavericks',10],['5','Josh Huestis','Oklahoma City Thunder',10],['6','T.J. McConnell','Philadelphia 76ers',10],['7','James Ennis','Memphis Grizzlies',10],['8','Walter Tavares','Atlanta Hawks',10],['9','Alex Len','Phoenix Suns',10],['10','Allen Crabbe','Portland Trail Blazers',10],['11','Noah Vonleh','Portland Trail Blazers',10],['12','Aaron Harrison','Charlotte Hornets',10],['13','Kevon Looney','Golden State Warriors',10],['14','Tristan Thompson','Cleveland Cavaliers',10],['15','C.J. Miles','Indiana Pacers',10],['16','Dirk Nowitzki','Dallas Mavericks',10],['17','Kyle O\'Quinn','New York Knicks',10],['18','Jeff Withey','Utah Jazz',10],['19','Jonas Valanciunas','Toronto Raptors',10],['20','Rashad Vaughn','Milwaukee Bucks',10],['21','Seth Curry','Dallas Mavericks',10],['22','Deron Williams','Dallas Mavericks',10],['23','D\'Angelo Russell','Los Angeles Lakers',10],['24','Kelly Olynyk','Boston Celtics',10],['25','Michael Carter-Williams','Milwaukee Bucks',10],['26','Devin Harris','Dallas Mavericks',10],['27','Matthew Dellavedova','Milwaukee Bucks',10],['28','Montrezl Harrell','Houston Rockets',10],['29','Draymond Green','Golden State Warriors',10],['30','Langston Galloway','New Orleans Pelicans',10],['31','Glenn Robinson III','Indiana Pacers',10],['32','Robert Covington','Philadelphia 76ers',10],['33','Bobby Portis','Chicago Bulls',10],['34','Festus Ezeli','Portland Trail Blazers',10],['35','Jared Dudley','Phoenix Suns',10],['36','Justise Winslow','Miami Heat',10],['37','Shabazz Muhammad','Minnesota Timberwolves',10],['38','Jarell Martin','Memphis Grizzlies',10],['39','Terrence Jones','New Orleans Pelicans',10],['40','Timofey Mozgov','Los Angeles Lakers',10],['41','Al-Farouq Aminu','Portland Trail Blazers',10],['42','Khris Middleton','Milwaukee Bucks',10],['43','Tyus Jones','Minnesota Timberwolves',10],['44','Rodney Stuckey','Indiana Pacers',10],['45','Luc Mbah a Moute','Los Angeles Clippers',10],['46','Brandon Rush','Minnesota Timberwolves',10],['47','James Young','Boston Celtics',10],['48','Avery Bradley','Boston Celtics',10],['49','Kristaps Porzingis','New York Knicks',10],['50','Anthony Bennett','Brooklyn Nets',10]
  ] },
  // Timeless Treasures Materials Signatures + Prime (25 cards each = 50 total, AUTO+MEM)
  { n: 'Timeless Treasures Materials Signatures', m: true, c: [
    ['1','Brandon Ingram','Los Angeles Lakers',99],['2','Kris Dunn','Minnesota Timberwolves',99],['3','Buddy Hield','New Orleans Pelicans',99],['4','Jaylen Brown','Boston Celtics',99],['5','Jamal Murray','Denver Nuggets',99],['6','Marquese Chriss','Phoenix Suns',99],['7','Thon Maker','Milwaukee Bucks',99],['8','Denzel Valentine','Chicago Bulls',99],['9','Wade Baldwin IV','Memphis Grizzlies',99],['10','Malachi Richardson','Sacramento Kings',99],['11','Dragan Bender','Phoenix Suns',99],['12','Kevin Durant','Golden State Warriors',49],['13','Kyrie Irving','Cleveland Cavaliers',49],['14','Carmelo Anthony','New York Knicks',49],['15','D\'Angelo Russell','Los Angeles Lakers',49],['16','Karl-Anthony Towns','Minnesota Timberwolves',49],['17','Dirk Nowitzki','Dallas Mavericks',49],['18','Mark Price','Cleveland Cavaliers',49],['19','Dan Issel','Kentucky Colonels (ABA)',49],['20','Jim Jackson','Dallas Mavericks',49],['21','Glen Rice','Miami Heat',49],['22','Dennis Scott','Orlando Magic',49],['23','Bill Laimbeer','Detroit Pistons',49],['24','Dikembe Mutombo','Denver Nuggets',49],['25','Jeff Hornacek','Utah Jazz',49]
  ] },
  { n: 'Timeless Treasures Materials Signatures Prime', p: true, b: 'Timeless Treasures Materials Signatures', m: true, c: [
    ['1','Brandon Ingram','Los Angeles Lakers',25],['2','Kris Dunn','Minnesota Timberwolves',25],['3','Buddy Hield','New Orleans Pelicans',25],['4','Jaylen Brown','Boston Celtics',25],['5','Jamal Murray','Denver Nuggets',25],['6','Marquese Chriss','Phoenix Suns',25],['7','Thon Maker','Milwaukee Bucks',25],['8','Denzel Valentine','Chicago Bulls',25],['9','Wade Baldwin IV','Memphis Grizzlies',25],['10','Malachi Richardson','Sacramento Kings',25],['11','Dragan Bender','Phoenix Suns',25],['12','Kevin Durant','Golden State Warriors',5],['13','Kyrie Irving','Cleveland Cavaliers',5],['14','Carmelo Anthony','New York Knicks',5],['15','D\'Angelo Russell','Los Angeles Lakers',5],['16','Karl-Anthony Towns','Minnesota Timberwolves',5],['17','Dirk Nowitzki','Dallas Mavericks',5],['18','Mark Price','Cleveland Cavaliers',5],['19','Dan Issel','Kentucky Colonels (ABA)',5],['20','Jim Jackson','Dallas Mavericks',5],['21','Glen Rice','Miami Heat',5],['22','Dennis Scott','Orlando Magic',5],['23','Bill Laimbeer','Detroit Pistons',5],['24','Dikembe Mutombo','Denver Nuggets',5],['25','Jeff Hornacek','Utah Jazz',5]
  ] },
];

async function main() {
  console.log('Importing remaining autograph sets (Batch 2)...\n');

  const release = await prisma.release.findUnique({ where: { slug: '2016-17-panini-donruss-basketball' } });
  if (!release) throw new Error('Release not found');

  const setSlugMap = new Map<string, string>();
  let totalSets = 0, totalCards = 0;

  for (const s of sets) {
    console.log(`Processing: ${s.n} (${s.c.length} cards)...`);
    
    const setSlug = generateSetSlug('2016-17', 'Donruss Basketball', s.n, 'Autograph', s.p ? 'parallel' : undefined);
    setSlugMap.set(s.n, setSlug);
    
    const existing = await prisma.set.findUnique({ where: { slug: setSlug } });
    if (existing) { console.log(`  ⚠️  Already exists\n`); continue; }
    
    const set = await prisma.set.create({
      data: {
        slug: setSlug, name: s.n, type: 'Autograph', releaseId: release.id,
        isParallel: s.p || false, baseSetSlug: s.b ? setSlugMap.get(s.b) || null : null
      }
    });
    
    totalSets++;
    let created = 0;
    
    for (const [num, player, team, pr] of s.c) {
      const variant = s.n.includes('Black') ? 'Black' : s.n.includes('Gold') ? 'Gold' : s.n.includes('Green') ? 'Green' : s.n.includes('Prime') ? 'Prime' : null;
      const slug = generateCardSlug('Panini', 'Donruss Basketball', '2016-17', s.n, num, player, variant, pr, 'Autograph');
      
      await prisma.card.create({
        data: {
          slug, playerName: player, team, cardNumber: num, setId: set.id, variant,
          printRun: pr, isNumbered: pr !== null, numbered: fmtNum(pr), rarity: calcRarity(pr),
          hasAutograph: true, hasMemorabilia: s.m || false
        }
      });
      created++;
    }
    
    totalCards += created;
    console.log(`  ✓ Created ${created} cards\n`);
  }

  console.log(`\n✅ Complete! Sets: ${totalSets}, Cards: ${totalCards}`);
}

main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
